# Credit Risk Project
## Phase 3 – Data Understanding

In [1]:
### 1. Import Libraries
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [2]:
connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Roxy@1994",   
    host="localhost",
    port=3306,
    database="credit_risk"
)

engine = create_engine(connection_url)

print("Connection Successful!")

Connection Successful!

In [3]:
### 3. load tables
application_train_df=pd.read_sql('select * from application_train',
                                 con=engine)

In [4]:
application_train_df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,,,,,,
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
### 3. verify data
application_train_df.shape

(307511, 122)

In [6]:
application_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(13), int64(41), object(68)
memory usage: 286.2+ MB

In [7]:
pd.set_option('display.float_format', '{:,.2f}'.format)

In [8]:
application_train_df.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21
count,"307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00",...,"307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00","307,511.00"
mean,"278,180.52",0.08,0.42,"168,797.92","599,026.00","27,107.52","537,909.48",0.02,"-16,037.00","63,815.05",...,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00
std,"102,790.18",0.27,0.72,"237,123.15","402,490.78","14,494.44","369,633.75",0.01,"4,363.99","141,275.77",...,0.00,0.06,0.05,0.03,0.10,0.02,0.09,0.02,0.02,0.02
min,"100,002.00",0.00,0.00,"25,650.00","45,000.00",0.00,0.00,0.00,"-25,229.00","-17,912.00",...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,"189,145.50",0.00,0.00,"112,500.00","270,000.00","16,524.00","238,500.00",0.01,"-19,682.00","-2,760.00",...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,"278,202.00",0.00,0.00,"147,150.00","513,531.00","24,903.00","450,000.00",0.02,"-15,750.00","-1,213.00",...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,"367,142.50",0.00,1.00,"202,500.00","808,650.00","34,596.00","679,500.00",0.03,"-12,413.00",-289.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,"456,255.00",1.00,19.00,"117,000,000.00","4,050,000.00","258,025.50","4,050,000.00",0.07,"-7,489.00","365,243.00",...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [9]:
application_train_df.isnull().sum().sort_values(ascending=False).head(20)

SK_ID_CURR                      0
OBS_30_CNT_SOCIAL_CIRCLE        0
WALLSMATERIAL_MODE              0
TOTALAREA_MODE                  0
HOUSETYPE_MODE                  0
FONDKAPREMONT_MODE              0
NONLIVINGAREA_MEDI              0
NONLIVINGAPARTMENTS_MEDI        0
LIVINGAREA_MEDI                 0
LIVINGAPARTMENTS_MEDI           0
LANDAREA_MEDI                   0
FLOORSMIN_MEDI                  0
FLOORSMAX_MEDI                  0
ENTRANCES_MEDI                  0
ELEVATORS_MEDI                  0
COMMONAREA_MEDI                 0
YEARS_BUILD_MEDI                0
YEARS_BEGINEXPLUATATION_MEDI    0
BASEMENTAREA_MEDI               0
APARTMENTS_MEDI                 0
dtype: int64

In [10]:
application_train_df[['OWN_CAR_AGE', 'EXT_SOURCE_1']].head(10)

  OWN_CAR_AGE         EXT_SOURCE_1
0              0.08303696739132256
1               0.3112673113812225
2        26.0
3
4
5
6        17.0   0.7747614130547695
7         8.0
8               0.5873340468730377
9

In [11]:
application_train_df['OWN_CAR_AGE'].unique()[:10]

array(['', '26.0', '17.0', '8.0', '23.0', '7.0', '14.0', '1.0', '3.0',
       '13.0'], dtype=object)

In [12]:
(application_train_df['OWN_CAR_AGE'] == '').sum()

np.int64(202929)